// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPage'](arg1, arg2, arg3, arg4);
}

export function ConnectToDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToDevice'](arg1, arg2, arg3);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function FetchPageContent(arg1) {
  return window['go']['main']['App']['FetchPageContent'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDbPages() {
  return window['go']['main']['App']['GetDbPages']();
}

export function GetDiscoveredDevices() {
  return window['go']['main']['App']['GetDiscoveredDevices']();
}

export function HardDeletePage(arg1) {
  return window['go']['main']['App']['HardDeletePage'](arg1);
}

export function MovePage(arg1, arg2) {
  return window['go']['main']['App']['MovePage'](arg1, arg2);
}

export function RestorePage(arg1) {
  return window['go']['main']['App']['RestorePage'](arg1);
}

export function StartUdpDiscovery() {
  return window['go']['main']['App']['StartUdpDiscovery']();
}

export function StopUdpDiscovery() {
  return window['go']['main']['App']['StopUdpDiscovery']();
}

export function UpdatePage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePage'](arg1, arg2, arg3, arg4, arg5);
}
