// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCard(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddPage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConnectToDevice(arg1:string,arg2:number,arg3:string):Promise<void>;

export function CreateWorkspace(arg1:string):Promise<void>;

export function DeleteCard(arg1:string,arg2:string):Promise<void>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeletePage(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function FetchCards(arg1:string):Promise<void>;

export function GetActiveWorkspace():Promise<string>;

export function GetCards(arg1:string):Promise<Array<main.Card>>;

export function GetConnectionStatus():Promise<string>;

export function GetDbPages():Promise<Array<main.DbPage>>;

export function GetDiscoveredDevices():Promise<Array<main.DiscoveredDevice>>;

export function GetImage(arg1:string):Promise<string>;

export function HardDeletePage(arg1:string):Promise<void>;

export function ListWorkspaces():Promise<Array<string>>;

export function MovePage(arg1:string,arg2:string):Promise<void>;

export function ReorderCards(arg1:string,arg2:Array<string>):Promise<void>;

export function RestorePage(arg1:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function StartUdpDiscovery():Promise<void>;

export function StopUdpDiscovery():Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<void>;

export function UpdateCard(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdatePage(arg1:string,arg2:string,arg3:string):Promise<void>;
