// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCard'](arg1, arg2, arg3);
}

export function AddPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPage'](arg1, arg2, arg3, arg4);
}

export function ConnectToDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToDevice'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteCard(arg1, arg2) {
  return window['go']['main']['App']['DeleteCard'](arg1, arg2);
}

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function FetchCards(arg1) {
  return window['go']['main']['App']['FetchCards'](arg1);
}

export function GetActiveWorkspace() {
  return window['go']['main']['App']['GetActiveWorkspace']();
}

export function GetCards(arg1) {
  return window['go']['main']['App']['GetCards'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDbPages() {
  return window['go']['main']['App']['GetDbPages']();
}

export function GetDiscoveredDevices() {
  return window['go']['main']['App']['GetDiscoveredDevices']();
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function HardDeletePage(arg1) {
  return window['go']['main']['App']['HardDeletePage'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function MovePage(arg1, arg2) {
  return window['go']['main']['App']['MovePage'](arg1, arg2);
}

export function ReorderCards(arg1, arg2) {
  return window['go']['main']['App']['ReorderCards'](arg1, arg2);
}

export function RestorePage(arg1) {
  return window['go']['main']['App']['RestorePage'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function StartUdpDiscovery() {
  return window['go']['main']['App']['StartUdpDiscovery']();
}

export function StopUdpDiscovery() {
  return window['go']['main']['App']['StopUdpDiscovery']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function UpdateCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCard'](arg1, arg2, arg3);
}

export function UpdatePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePage'](arg1, arg2, arg3);
}
