// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddItem(arg1:string,arg2:string):Promise<void>;

export function ConnectToDevice(arg1:string,arg2:number):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConnectionStatus():Promise<string>;

export function GetDbItems():Promise<Array<main.DbItem>>;

export function GetDiscoveredDevices():Promise<Array<main.DiscoveredDevice>>;

export function StartUdpDiscovery():Promise<void>;

export function StopUdpDiscovery():Promise<void>;

export function UpdateItem(arg1:string,arg2:string,arg3:string):Promise<void>;
