// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2) {
  return window['go']['main']['App']['AddItem'](arg1, arg2);
}

export function ConnectToDevice(arg1, arg2) {
  return window['go']['main']['App']['ConnectToDevice'](arg1, arg2);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDbItems() {
  return window['go']['main']['App']['GetDbItems']();
}

export function GetDiscoveredDevices() {
  return window['go']['main']['App']['GetDiscoveredDevices']();
}

export function StartUdpDiscovery() {
  return window['go']['main']['App']['StartUdpDiscovery']();
}

export function StopUdpDiscovery() {
  return window['go']['main']['App']['StopUdpDiscovery']();
}

export function UpdateItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3);
}
